### ISSUE TITLE
demo uses non-existent code

### ISSUE THREAD

**Issue by videlec** [flatsurf/ipyvue-flatsurf#70]
Samuel Lelièvre [said](https://sagemath.zulipchat.com/#narrow/stream/271193-polygon/topic/No.20Meeting.202022.2E07.2E26/near/291016461):

    Visiting https://github.com/flatsurf/ipyvue-flatsurf and clicking the binder demo button,
    the example notebooks are failing with:

    ImportError: cannot import name 'Decomposition' from 'flatsurf.geometry.gl2r_orbit_closure' (/srv/conda/envs/notebook/lib/python3.9/site-packages/flatsurf/geometry/gl2r_orbit_closure.py)

This was indeed removed in commit 11c44e5 from [PR#128](https://github.com/flatsurf/sage-flatsurf/pull/128).

**Comment by slel** [comment]
This seems to have been fixed now.

**Comment by videlec** [comment]
> `A = matrix([v0, v1])`

Are these [pyflatsurf.vector.Vector](https://github.com/flatsurf/flatsurf/blob/master/pyflatsurf/src/pyflatsurf/vector.py#L38)? If so you can use
```
P = v0.parent()._isomorphic_vector_space
A = matrix([P(v0), P(v1)])
```
Though it is not extremely user friendly...

**Comment by videlec** [comment]
These are actually (wrapped) vectors from the libflatsurf library. You need to use the even more complicated
```
P = O.V2._isomorphic_vector_space
A = matrix([P(O.V2(v0)), P(O.V2(v1))])
```

**Comment by slel** [comment]
Thanks, my attempts had been unsuccessful, having 
explored neither `O`'s methods nor hidden methods.

Pushed another commit to #71 completing the fix.
